spring.application.name=gym-crm

logging.level.com.giorgi.gymcrm=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/gymcrm
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
logging.level.org.hibernate.SQL=DEBUG